
# nmake makefile to create vwin32.exe.
# vwin32.exe will work in win9x only.
# tools used:
#  - jwasm  (v2.16 needed)
#  - wrc    (the resource compiler supplied with Open Watcom)

name = vwin32

outd=Release

ALL: $(outd) $(outd)\$(name).exe

$(outd):
	@mkdir $(outd)

$(outd)\$(name).exe: $(name).asm Makefile rsrc.rc
	@jwasm -nologo -pe -Sg -c -Fl$* -Fo$* -IInclude $(name).asm
	@wrc -q -bt=nt -i=Include -fo=$(outd)\rsrc.res rsrc.rc $*.exe

clean:
	del $(outd)\*.exe
	del $(outd)\*.res
	del $(outd)\*.lst
