
#define IDC_STATIC -1

#define IDD_DIALOG1                     101
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define IDC_EDIT9                       1008
#define IDC_EDIT10                      1009
#define IDC_EDIT11                      1010
#define IDC_EDIT12                      1011
#define IDC_EDIT13                      1012
#define IDC_STATIC1                     1020
#define IDC_STATIC2                     1021
#define IDC_STATIC3                     1022
#define IDC_STATIC4                     1023
#define IDC_STATIC5                     1024
#define IDC_STATIC6                     1025
#define IDC_STATIC7                     1026
#define IDC_STATIC8                     1027
#define IDC_STATIC9                     1028
#define IDC_STATIC10                    1029
#define IDC_STATIC11                    1030
#define IDC_STATIC12                    1031
#define IDC_STATIC13                    1032
#define IDC_RADIO1                      1040
#define IDC_RADIO2                      1041
#define IDC_RADIO3                      1042

